apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: ms/service-b:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "person-events"
            - name: KAFKA_GROUP_ID
              value: "service-b"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
